spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://hahahoho.mysql.database.chinacloudapi.cn:3306/baby_back?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: jansona@hahahoho
    password: 2ale0LI1pona9

    druid: 
      test-on-borrow: true

jasypt:
  encryptor:
    password: hahahohohehe
