spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jansona@gugugu
    password: ENC(vEJKeKNvw2YZvXSmCo+JR6HNJ7kLg6Mc)
    url: jdbc:mysql://gugugu.mysql.database.chinacloudapi.cn:3306/baby_back?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

    druid: 
      test-on-borrow: true

jasypt:
  encryptor:
    password: hahahohohehe
