spring:
  datasource:
    url: jdbc:mysql://gugugu.mysql.database.chinacloudapi.cn:3306/baby_back?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: jansona@gugugu
    password: ENC(vEJKeKNvw2YZvXSmCo+JR6HNJ7kLg6Mc)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #  在控制台显示数据
    show-sql: false
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow


  redis:
 #   host: gugugu.redis.cache.chinacloudapi.cn
    host: 127.0.0.1
    port: 6379
 #   password: rrOmlWrNSerY9amDRcdXeRsClNwD363FHye9OdFOaQI=
  #  ssl: true
    timeout: 10000


jasypt:
  encryptor:
    password: hahahohohehe

